# Netlify configuration file, follwing guidance at ...
# https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/

[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.62.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.62.2"